#eureka集群使用
#
#在一个分布式系统中，服务注册中心是最重要的基础部分，理应随时处于可以提供服务的状态。
#如果是单点部署，如果注册中心出现故障，将会出现毁灭性的灾难。
#为了维持其可用性，使用集群是很好的解决方案。
#Eureka通过互相注册的方式来实现高可用的部署，所以我们只需要将Eureke Server配置其他可用的serviceUrl就能实现高可用部署。
#
#新建集群配置profiles：application-peer1.yml/application-peer2.yml/application-peer3.yml

#配置pom文件，添加集群
#配置peer1,peer2,peer3地址：Windows系统修改C:/WINDOWS/system32/drivers/etc/hosts文件，增加：
#   127.0.0.1       localhost
#	127.0.0.1       peer1
#	127.0.0.1       peer2
#	127.0.0.1       peer3


server:
  port: 8761


eureka:
  instance:
    hostname: peer1
  client:
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
    #默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/


spring:
  application:
  name: eureka-server-peer1
