server:
  port: 8085

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/springboot?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
#serverTimezone=GMT%2B8 时区：东八区

mybatis:
  type-aliases-package: com.example.mybatisdemo.entity
  mapper-locations: classpath:mapping/*Mapper.xml

#showSql
logging:
  level:
    com:
      example:
        mybatisdemo:
          mapper: debug